### ISSUE TITLE
Call dba.configureLocalInstance() for MySQL 5.7 support

### ISSUE THREAD

**Issue by prydie** [oracle/mysql-operator#145]
The v0.1.x release series was previously intended to be the only series to support MySQL 5.7 due to perceived incompatibilities in `mysqlsh`, however,  in actuality, `mysqlsh` is backwards compatible. 

The only difference is that with MySQL 5.7 you must call `dba.configureLocalInstance()`, locally, on each member of the cluster after any topology change to ensure that the cluster configs are persisted in the mysqld conf files (see: https://dev.mysql.com/doc/refman/5.7/en/mysql-innodb-cluster-production-deployment.html#configuring-the-instance-id).

This also means that members will automatically rejoin the cluster on restart without the need for `mysql-agent` intervention.

**Comment by gianlucaborello** [comment]
FYI, I have been having several difficulties using MySQL 5.7 with the current operator (I spoke too soon when I said it was working, as I didn't do proper failure testing), to the point where I'm likely going to switch to 8 moving forward, if I can. Some of the issues are:

1) Logic in `RebootClusterFromCompleteOutage()` triggers an error in 5.7, since the syntax `RESET PERSIST group_replication_bootstrap_group` is not supported

2) A failure of the first statefulset instance is not handled well: in the `bootstrap()` function, we look for the `(metadata exists, but GR is not active)` message to check if the cluster already exists or not, however, that message never seems to show up under 5.7 upon restart, even if I manually issue a `dba.configureLocalInstance()` (but I might be doing it wrong). So, the code tries to bootstrap a new cluster, leading to the error:

```
SystemError: ArgumentError: Dba.create_cluster: A Cluster with the name 'Cluster' already exists.
```

To fix the situation, I have to manually use Shell and issue a `dba.rebootClusterFromCompleteOutage()`.

So, for now I'm focusing on 8.0.

**Comment by owainlewis** [comment]
Closing this because we won't support for the 8.0 release.
