### ISSUE TITLE
version 0.2.0 doesn't work with Spinnaker (0.1.1 does)

### ISSUE THREAD

**Issue by jareksm** [oracle/mysql-operator#191]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**MySQL Operator Version**: 0.2.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.10.4
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS
- **Kernel** (e.g. `uname -a`): 4.14.48-coreos-r2
- **Others**: Spinnaker 1.8.3 (spinnaker.io)

## What happened?
When using spinnaker to deploy k8s manifest to create a cluster, it recognises it as cluster kind. After deploying the manifest it can't query to see if it has been deployed, since the crd is mysqlcluster and not cluster. Using 2 names for the kind/crd is resource definition introduced in commit 2944c3d90 breaks CD tools like Spinnaker.

## What you expected to happen?
Using version 0.1.1 of mysql-operator works as expected. Since Spinnaker deploys MySQLCluster kind and then it can query for mysqlcluster crd and get the correct results.

## How to reproduce it (as minimally and precisely as possible)?
Use spinnaker pipeline to deploy any manifest using mysql-operator v0.2.0. 

## Anything else we need to know?
Decide on using either cluster or mysqlcluster kinds/crd. Same applies to backup, restore and backupschedule.

**Comment by prydie** [comment]
Thanks for the bug report @jareksm.

If I'm understanding the issue correctly I believe this is a bug in Spinnaker rather than in the MySQL Operator. We have moved to prefixless Kinds as they are namespaced under our API Group and we use prefixed singular/plural names to disambiguate as `cluster`, `backup`, and `backupschedule` would otherwise be contended names.

To the best of my knowledge, the 0.2.0 CRDs follow the current best practice and I recommend opening a bug with Spinnaker.
